mod_id=cnpclines
mod_jar_name=cnpclines-1.12.2Forge
mod_name=CNPC Lines
mod_group=top.cnpclines
mod_version=1.0.0
mod_author=["XiaoBiniaoX"]
mod_description=Custom NPCs 消息浮层移植：/binnpclines open CustomMessageOverlay 指令与 HUD 消息浮层 UI
minecraft_version=1.12.2
forge_version=14.23.5.2860
mappings_channel=snapshot
mappings_version=20180814-1.12
mod_mixin_configs=mixins.${mod_id}.json
mod_mixin_refmap=refmap.${mod_id}.json
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
